version: '3'
services:
  node:
    image: dtizonportilla/orbis-training-docker:2.0.0
    build: .
    ports:
      - 3030:1042
    command: npm start
    volumes: 
      - $PWD:/app
  test:
    image: node:10.10.0-slim
    command: curl node:1042
  